### ISSUE TITLE
cannot build my yaml files in the HA ESP home

### ISSUE THREAD

**Issue by barosan909** [geertmeersman/nexxtender#73]
through reading the readme I managed to build this yaml file.. which seems to be erroneous. 

could you please guide on how many yaml files in the end are needed, which one is for the esp32 and if you could share an example of you config (please be careful with sensitive data)

Here is my config that is not working...

```
esphome:
  name: nexxtender
  friendly_name: nexxtender

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_GATTC_NOTIF_REG_MAX: "32"
    packages:
       nexxtender:
        url: https://github.com/geertmeersman/nexxtender
        file: config/nexxtender.yaml
        refresh: 0s
    substitutions:
      ## Uncomment and modify when you want to use a different device name.
       device_name: nexxtender
       friendly_name: Nexxtender
      ## Uncomment and modify when you want to use a different threshold.
       charging_mode_eco_threshold: "8"      # Single phase (6A + 2 margin)
       charging_mode_eco_bi_threshold: "14"  # Bi-phase (12A + 2 margin)
       charging_mode_eco_tri_threshold: "20" # Tri-phase (18A + 2 margin)
       slider_max_car_charging_speed: "32"     # The max value of the slider for the maximum car charging speed slider, default set to 32
       slider_max_available_capacity: "40"     # The max value of the slider for the maximum available capacity slider, default set to 40
       slider_max_peak_consumption_limit: "40" # The peak consumption limit for the slider (in amperes, typically 16-40A). WARNING: Incorrect values may cause circuit breaker trips or reduced charging performance. This value is usually configured by your installer.
       min_charging_value: "6" # The minimal charging value, used for the slider configs
       slider_max_offloading_minimum: "32" # The max offloading minimum value
       slider_min_offloading_minimum: "6" # The min offloading minimum value

    # Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:
```

**Comment by geertmeersman** [comment]
Just try with
```yaml
packages:
  nexxtender:
    url: https://github.com/geertmeersman/nexxtender
    file: config/nexxtender.yaml
    refresh: 0s
```
